---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
## Loading required package: viridisLite
library(p8105.datasets)
library(plotly)
```

```{r importing_rest_insp}
library(tidyverse)
library(httr)
library(jsonlite)

get_all_inspections = function(url) {
  
  all_inspections = vector("list", length = 0)
  
  loop_index = 1
  chunk_size = 50000
  DO_NEXT = TRUE
  
  while (DO_NEXT) {
    message("Getting data, page ", loop_index)
    
    all_inspections[[loop_index]] = 
      GET(url,
          query = list(`$order` = "zipcode",
                       `$limit` = chunk_size,
                       `$offset` = as.integer((loop_index - 1) * chunk_size)
                       )
          ) %>%
      content("text") %>%
      fromJSON() %>%
      as_tibble()
    
    DO_NEXT = dim(all_inspections[[loop_index]])[1] == chunk_size
    loop_index = loop_index + 1
  }
  
  all_inspections
  
}

url = "https://data.cityofnewyork.us/resource/9w7m-hzhe.json"

nyc_inspections = get_all_inspections(url) %>%
  bind_rows() 
```



```{r}
nyc_inspections %>% 
  group_by(boro, grade) %>% 
  summarize(n = n()) %>% 
  spread(key = grade, value = n)
```

```{r}
rest_inspec =
  nyc_inspections %>%
  filter(grade %in% c("A", "B", "C"), boro != "Missing") %>% 
  mutate(boro = str_to_title(boro))
```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
eth = rest_inspec %>% 
  filter (cuisine_description %in% c("Chinese", "French", "Japanese", "Indian", "Italian")) %>% 
  group_by (boro, cuisine_description) %>% 
  summarize (n = n()) %>% 
  ggplot(aes(x = cuisine_description, y=n, fill = boro)) +
  geom_bar(stat="identity") + facet_wrap(~ boro, ncol=2) +
  labs (
    title = "Frequency of Select Ethnic Restaurants By Borough",
        x = "Cuisine Type",
        y = "Frequency"
  ) + theme(axis.text.x = element_text(angle = 75, hjust = 1)) + theme(legend.position="none")

eth = ggplotly(eth)
eth
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
rest_clean = rest_inspec %>% 
  separate(grade_date, into = c("year", "month", "date"), sep = "-") %>%
  separate(date, into = c("date", "remove"), sep = 2) %>%
  select (boro, cuisine_description, grade, year, month, date, camis, score) %>%   mutate(year = as.numeric(year))
rest = rest_clean %>% 
  filter (year > 2013) %>% 
  filter (grade == "A") %>%
  group_by (boro, year) %>% 
  summarize (count = n()) %>% 
  ggplot (aes(x = year, y = count, color = boro)) +
    geom_line () + geom_point() +
  labs (
    title = "Frequency of Total Number of A Grades Assigned",
        x = "Year",
        y = "Frequency"
  )
rest = ggplotly(rest)
rest
```

### Chart C

```{r}
rest_score = rest_clean %>% 
  select(boro, grade, year, camis, score) %>% 
  mutate(score = as.numeric(score)) %>% 
  filter (year > 2014) %>% 
  filter (year < 2018) %>% 
  mutate(year = as.character(year)) %>% 
  ggplot(aes(x = year, y = score, fill = year)) +
  geom_boxplot() +
  theme_classic() + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs (
    title = "Summary of Scores By Year",
        x = "Year",
        y = "Score"
  )

rest_score = ggplotly(rest_score)
rest_score
```


